### ISSUE TITLE
Login form server address

### ISSUE THREAD

**Issue by Toshbrown** [me-box/core-ui#1]
The login form defaults the server address to 127.0.0.1. This causes confusion if people access databox using localhost, an IP address or hostname as the login fails even if the password is correct. 

@ktg is it possible to auto-fill this field from the browser URL? 

If so can you do this in the new updated UI?

**Comment by ktg** [comment]
Yup. Already done.
Well... technically its never been tested on anything other than localhost yet. But it is just filling in the host from the browser url, so I'm not really sure how wrong this could go...

**Comment by ktg** [comment]
Hahaha.
There was totally a bug in this

**Comment by mor1** [comment]
...it sounds possible that a more complete testing regime may be in order then?

**Comment by Toshbrown** [comment]
Fixed in 0.5.2-dev branch so should be fixed in the next release
